unknown: bin
001_chips_can: long_table_a
002_master_chef_can: long_table_a
003_cracker_box: long_table_a
004_sugar_box: long_table_a
005_tomato_soup_can: long_table_a
006_mustard_bottle: long_table_a
007_tuna_fish_can: long_table_a
008_pudding_box: long_table_a
009_gelatin_box: long_table_a
010_potted_meat_can: long_table_a
011_banana: long_table_a
012_strawberry: long_table_a
013_apple: long_table_a
014_lemon: long_table_a
015_peach: long_table_a
016_pear: long_table_a
017_orange: long_table_a
018_plum: long_table_a
019_pitcher_base: container_b
021_bleach_cleanser: container_b
022_windex_bottle: container_b
023_wine_glass: container_b
024_bowl: container_b
025_mug: container_b
026_sponge: container_b
027-skillet: bin_a
028_skillet_lid: bin_a
029_plate: container_b
030_fork: container_b
031_spoon: container_b
032_knife: bin_a
033_spatula: container_b
035_power_drill: bin_a
036_wood_block: bin
037_scissors: bin_a
038_padlock: bin_a
039_key: bin_a
040_large_marker: bin_a
041_small_marker: bin_a
042_adjustable_wrench: bin_a
043_phillips_screwdriver: bin_a
044_flat_screwdriver: bin_a
046_plastic_bolt: bin_a
047_plastic_nut: bin_a
048_hammer: bin_a
049_small_clamp: bin_a
050_medium_clamp: bin_a
051_large_clamp: bin_a
052_extra_large_clamp: bin_a
053_mini_soccer_ball: bin_a
054_softball: bin_a
055_baseball: bin_a
056_tennis_ball: bin_a
057_racquetball: bin_a
058_golf_ball: bin_a
059_chain: bin_a
061_foam_brick: bin_a
062_dice: bin_a
063-a_marbles: bin_a
065-a_cups: bin_a
070-a_colored_wood_blocks: bin_a
071_nine_hole_peg_test: bin_a
072-a_toy_airplane: bin_a
073-a_lego_duplo: bin_a
076_timer: bin_a
077_rubiks_cube: bin_a
